services:
    developers_sprint03:
        depends_on:
            - mysql
        container_name: developers-backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./DevelopersTeamEx/:/var/www/html
        command: >
            bash -c "cd /var/www/html/
            && composer upgrade && composer update && composer install && /usr/sbin/apachectl -D FOREGROUND"
        networks:
            - sprint03_network

    mysql:
        container_name: sprint03-mysql
        image: mysql:8.0.37-debian
        environment:
            MYSQL_DATABASE: tasks_database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - ./docker/mysql-data:/var/lib/mysql
            - ./docker/config/mysql_ini:/docker-entrypoint-initdb.d
            - ./docker/config/mysql/my.cnf:/etc/my.cnf
        networks:
            - sprint03_network

networks:
    sprint03_network:
