<!DOCTYPE html>
<html>
	<head>
		<title>Dude's Tasks Application</title>
		<script type="text/javascript" src="<?php echo get_javascript('jquery-3.7.1.js');?>"></script>
		<script type="text/javascript" src="<?php echo get_javascript('tailwind.config.js');?>"></script>
		<script type="text/javascript" src="<?php echo get_javascript('popUpMod.js');?>"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo get_stylesheet('indexStylesheet.css'); ?>">
	</head>
	<body>
		<?php echo $this->content(); ?>
   </body>
</html>
