
<header>
	<h2>Dude's Tasks Application</h2>
	<div class="addTaskDiv" >
		<button id="addTaskButton" onclick="addTaskFunction()">
		<a href="javascript:;"><i class="iconMod" style="<?php echo "background-image: url('" . get_png("addTaskPlus.png") ."')" ?>"></i></a>
		</button>
	</div>	
	
	<div class="taskSearcher">
		<form id="taskSearcherForm" method="post" >
			<input type="text" id="searchTaskForm" name="taskForm" value="search" hidden readonly>
			<input type="search" id="taskSeacherInput" name="taskSeacherInput" placeholder="Search...">
			<button>Search!</button>
		</form>
	</div>
	
	<div id="filters-container">
		<button id="filtersButton" onclick="filtersFunction()">
			<a href="javascript:;"><i class="filtersSel" style="<?php echo "background-image: url('" . get_png("filters.png") ."')" ?>"></i></a>
		</button>
	</div>
	
	
</header>

<main>
	<table id="tasksList">
		<thead id="headerTasksList">
			<tr>
			<th class="taskId hiddenRow">
				Task ID
			</th>
			<th class="taskCreator">
				Task Creator
			</th>
			<th class="taskType">
				Task Type
			</th>
			<th class="taskDescription">
				Task Description
			</th>
			<th class="taskCreationDate">
				Task Creation Date
			</th>
			<th class="taskFinalizationDate">
				Task Finalization Date
			</th>
			<th class="divMod">
				Modify 
			</th>
			<th class="divDel">
				Delete
			</th>
			</tr>			
		</thead>
		<!-- Starting List of Tasks Elements -->
		<tbody>
		
		<?php addListTaskIntoHTML($this)?>
		
			
		</tbody>
	</table>
	
	<?php addEmptyStateTable($this);?>
	<!-- Formular in order to be able to modify the tasks -->
	<div id="modFormDiv">
	<div id="innerModFormDiv">
	<div id="contentModFormDiv">
	<form action="#" method="post">
		<div class="groupForm">
			<input type="text" id="modTaskForm" class="formFieldHidden"  name="taskForm" value="modify" readonly>
			<div class="inputGroup">
				<label for="taskId">Task ID:</label><br>
				<input type="text" id="modTaskId" name="taskId" value="1" readonly>
			</div>
			
			<div class="inputGroup">
					<label for="taskCreator">Task Creator:</label><br>
					<input type="text" id="modTaskCreator" name="taskCreator" value="Dude">
			</div>
			
			<div class="inputGroup">
					<label for="taskType">Task Type:</label><br>
					<select id="modTaskType" name="taskType">
						<option value="Pending">Pending</option>
						<option value="Ongoing">Ongoing</option>
						<option value="Finished">Finished</option>
					</select>
			</div>
		
		</div>
		
		<div class="groupForm">
			<div class="inputGroup">
				<label for="taskDescription">Task Description:</label><br>
				<textarea rows="5" id="modTaskDescription" name="taskDescription" value="Finish the sprint 3 with JSON Persistency">
				</textarea><br>
			</div>
		</div>
		
		<div class="groupForm">
			<div class="inputGroup">
				<label for="creationDate">Creation Date of the task:</label><br>
				<input
					type="datetime-local"
					id="modCreationDate"
					name="creationDate"
					step="any"
					/>
			</div>
			<div class="inputGroup">
				<label for="finalizationDate">Finalization Date of the task:</label><br>
				<input
					type="datetime-local"
					id="modFinalizationDate"
					name="finalizationDate"
					step="any"
					/>
				</div>
			</div>
			
		<div class="groupForm">
			<div class="inputGroup">
				<button id="submitModForm" type="submit" name="submit"  value="modTask">Modify Task</button>
			</div>
		</div>
		
		
		<div class="groupForm">
			<div class="inputGroup">
				<button id="modFormCloseButton" onclick="closeFormPopUpFunction()">
				Cancel
				</button>
			</div>
		</div>
		
	</form>
		
	</div>
	</div>
	</div>
	
	<!-- Formular in order to be able to modify the tasks  END-->
	
	
	
	<!-- Formular in order to be able to add a task -->
	<div id="addFormDiv">
	<div id="innerAddFormDiv">
	<div id="contentAddFormDiv">
	<form action="#" method="post">
		<div class="groupForm">
			<input type="text" id="addTaskForm" class="formFieldHidden" name="taskForm" value="add" readonly>
			<div class="inputGroup">
				<label for="taskId">Task ID:</label><br>
				<input type="text" id="addTaskId" name="taskId" value="0" readonly>
			</div>
			
			<div class="inputGroup">
					<label for="taskCreator">Task Creator:</label><br>
					<input type="text" id="addTaskCreator" name="taskCreator" value="Dude">
			</div>
			
			<div class="inputGroup">
					<label for="taskType">Task Type:</label><br>
					<select id="addTaskType" name="taskType">
						<option value="Pending">Pending</option>
						<option value="Ongoing">Ongoing</option>
						<option value="Finished">Finished</option>
					</select>
			</div>
		
		</div>
		
		<div class="groupForm">
			<div class="inputGroup">
				<label for="taskDescription">Task Description:</label><br>
				<textarea rows="5" id="addTaskDescription" name="taskDescription">
				</textarea><br>
			</div>
		</div>
		
		<div class="groupForm">
			<div class="inputGroup">
				<label for="creationDate">Creation Date of the task:</label><br>
				<input
					type="datetime-local"
					id="addCreationDate"
					name="creationDate"
					step="any"
					/>
			</div>
			<div class="inputGroup">
				<label for="finalizationDate">Finalization Date of the task:</label><br>
				<input
					type="datetime-local"
					id="addFinalizationDate"
					name="finalizationDate"
					step="any"
					/>
				</div>
			</div>
			
		<div class="groupForm">
			<div class="inputGroup">
				<button id="submitAddForm" type="submit" name="submit" value="addTask">Add Task</button>
			</div>
		</div>
		
		
		<div class="groupForm">
			<div class="inputGroup">
				<button id="addFormCloseButton" onclick="closeAddFormPopUpFunction()">
				Cancel
				</button>
			</div>
		</div>
		
	</form>
		
	</div>
	</div>
	</div>
	
	<!-- Formular in order to be able to add a tasks  END-->
	
	<!-- HIDDEN Formular in order to be able to delete a task -->
	<!-- just javascript does not wanna work after 1000 tries -->
	<div id="delFormDiv">
	<div id="innerDelFormDiv">
	<div id="contentDelFormDiv">
	<form id="delForm" action="" method="post">
		<div class="groupForm">
			<div class="inputGroup">
				<label for="taskId">Task ID:</label><br>
				<input type="text" id="delTaskId" class="formFieldHidden" name="taskId" value="0" readonly>
				<!-- workaround.... -->
				<input type="text" id="delTaskForm" name="taskForm" value="delete" readonly>
			</div>
		</div>
			
		<div class="groupForm">
			<div class="inputGroup">
				
				
				<input type="submit" value="delTask">
				<!--<button id="submitDelForm" type="submit" name="btnSubmit" value="delTask">Add Task</button>-->
			</div>
		</div>
	
		
	</form>
		
	</div>
	</div>
	</div>
	
	<!-- Formular in order to be able to add a tasks  END-->
	
	
	
	<!-- HIDDEN Formular in order to be able to delete a task -->
	<!-- just javascript does not wanna work after 1000 tries -->
	<div id="filtersFormDiv">
	<div id="innerFiltersFormDiv">
	<div id="contentFiltersFormDiv">
	<form id="filtersForm" action="" method="post">
		<input type="text" id="filtersTaskForm" name="taskForm" value="filters" hidden readonly>
		<h2>Filters:</h2>
		<div class="groupForm">
			
			<div class="inputGroup">
				<label for="user">User:</label> </br>
				<input type="text" id="user" name="filtersUser">
			</div>
			
			<div class="inputGroup">
					<label for="addTaskType">Task Type:</label><br>
					<select id="addTaskType" name="filtersTaskType">
						<option value="Pending">Pending</option>
						<option value="Ongoing">Ongoing</option>
						<option value="Finished">Finished</option>
						<option value="All">All</option>
					</select>
			</div>

		</div>
			
		<div class="groupForm">
			<div class="inputGroup">
				
				
				<input type="submit" value="Apply Filters">
				<!--<button id="submitDelForm" type="submit" name="btnSubmit" value="delTask">Add Task</button>-->
			</div>
			<button id="filtersHideButton" onclick="filtersHideFunction()">
				<a href="javascript:;">Cancel</a>
			</button>
			
			
		</div>
	
		
	</form>
		
	</div>
	</div>
	</div>
	
	
	
	
	
</main>

<footer>
</footer>

